// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-kthrrqWVogQ_wrxBByd2m7U2P3LaWuo',
    appId: '1:940140289358:web:13fcd6cb20666776b1121f',
    messagingSenderId: '940140289358',
    projectId: 'kpp-labka-1700d',
    authDomain: 'kpp-labka-1700d.firebaseapp.com',
    storageBucket: 'kpp-labka-1700d.firebasestorage.app',
    measurementId: 'G-4T1N9Z0QEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkQ3n1WucnFlsbG2ECDfd-0LCirlJ_Fl8',
    appId: '1:940140289358:android:062ea3f3b2f213b8b1121f',
    messagingSenderId: '940140289358',
    projectId: 'kpp-labka-1700d',
    storageBucket: 'kpp-labka-1700d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiNXsMZfgV6J6ZHTQxfaCXUvwGdSITXKQ',
    appId: '1:940140289358:ios:d540a01cb4d2e7b5b1121f',
    messagingSenderId: '940140289358',
    projectId: 'kpp-labka-1700d',
    storageBucket: 'kpp-labka-1700d.firebasestorage.app',
    iosBundleId: 'com.example.kppLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiNXsMZfgV6J6ZHTQxfaCXUvwGdSITXKQ',
    appId: '1:940140289358:ios:d540a01cb4d2e7b5b1121f',
    messagingSenderId: '940140289358',
    projectId: 'kpp-labka-1700d',
    storageBucket: 'kpp-labka-1700d.firebasestorage.app',
    iosBundleId: 'com.example.kppLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-kthrrqWVogQ_wrxBByd2m7U2P3LaWuo',
    appId: '1:940140289358:web:e4b036b11acaadbfb1121f',
    messagingSenderId: '940140289358',
    projectId: 'kpp-labka-1700d',
    authDomain: 'kpp-labka-1700d.firebaseapp.com',
    storageBucket: 'kpp-labka-1700d.firebasestorage.app',
    measurementId: 'G-7TS710JL1R',
  );
}
